name: lkvitai-mes-manual

services:
  redis:
    image: redis:7.2-alpine
    container_name: lkvitai-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - lkvitai-mes_default

  api:
    image: ghcr.io/lauresta/lkvitai-mes-warehouse-api:${IMAGE_TAG:-latest}
    container_name: lkvitai-mes-warehouse-api
    restart: unless-stopped
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      ConnectionStrings__WarehouseDb: "Host=pg;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      SkipSchemaValidation: "true"
      Caching__RedisConnectionString: "lkvitai-redis:6379,abortConnect=false,connectRetry=3,connectTimeout=1000,syncTimeout=1000"
      ITEMIMAGES__ENDPOINT: "${ITEMIMAGES__ENDPOINT}"
      ITEMIMAGES__BUCKET: "${ITEMIMAGES__BUCKET}"
      ITEMIMAGES__USESSL: "${ITEMIMAGES__USESSL:-false}"
      ITEMIMAGES__ACCESSKEY: "${ITEMIMAGES__ACCESSKEY}"
      ITEMIMAGES__SECRETKEY: "${ITEMIMAGES__SECRETKEY}"
    networks:
      - lkvitai-mes_default
    depends_on:
      - redis

  webui:
    image: ghcr.io/lauresta/lkvitai-mes-warehouse-webui:${IMAGE_TAG:-latest}
    container_name: lkvitai-mes-warehouse-webui
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      WarehouseApi__BaseUrl: "http://lkvitai-mes-warehouse-api:8080"
    networks:
      - lkvitai-mes_default
    depends_on:
      - api

networks:
  lkvitai-mes_default:
    external: true
